#!/bin/sh

set -e

git submodule init
git submodule update

RUST_CMAKE_ARGS=""
(
  cd rust/avida-rust
  cargo build --release
)
RUST_LIB_PATH="$(pwd)/rust/avida-rust/target/release/libavida_rust.a"
RUST_CMAKE_ARGS="-DAVD_RUST_ENABLED:BOOL=ON -DAVD_RUST_LIB_PATH:FILEPATH=${RUST_LIB_PATH}"

do_build() {
  (
    mkdir -p cbuild
    cd cbuild
    cmake -DCMAKE_POLICY_VERSION_MINIMUM=3.20 ${RUST_CMAKE_ARGS} "$@" ../
    make -j 10 install
  )
}

do_build "$@" || {
    echo "build failed, trying again with backtrace support disabled"
    # If the command fails, set the environment variable and try again
    export AVIDA_DISABLE_BACKTRACE=1
    rm -rf cbuild
    do_build "$@"
}
